### ISSUE TITLE
Allow setting pgbouncer settings via FDW

### ISSUE THREAD

**Issue by keithf4** [CrunchyData/pgbouncer_fdw#4]
See if we can allow "writing back" to the pgbouncer sever with special views/functions that can do things like PAUSE/RESUME or other actions.

**Comment by davidfetter** [comment]
I did this in https://github.com/davidfetter/pgbouncer_warapper with `dblink`'s `dblink_exec()`, e.g.
```
/* DISABLE db */
CREATE FUNCTION pgbouncer.disable(db TEXT)
RETURNS VOID
LANGUAGE sql
AS $$
    SELECT dblink_exec('pgbouncer', pg_catalog.format('%s %I', 'disable', db));
$$;
COMMENT ON FUNCTION pgbouncer.disable(db TEXT) IS $$Reject all new client connections on the given database.$$;
```

**Comment by keithf4** [comment]
I actually just did a PR recently to add this. Forgot to close this issue. Thanks!

**Comment by keithf4** [comment]
Added in v0.3
